version: '3'

services:
  db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: our
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: our_user
      MYSQL_PASSWORD: fas32wrn239fn42f2
      TZ: Asia/Tokyo

  webpack:
    build: 
      context: .
      dockerfile: webapp/Dockerfile
    command: sh -c "npm install && npm run dev"  
    ports:
      - "3003:3003"
    volumes:
      - ./webapp:/webapp

  webapp:
    build: 
      context: .
      dockerfile: webapp/Dockerfile
    command: sh -c "puma -C config/puma.rb" 
    volumes:
      - ./webapp:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
      - webpack
    tty: true
    stdin_open: true
  
  web:
    build:
      context: ./
      dockerfile: ./webapp/containers/nginx/Dockerfile
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - webapp

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  