version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - run:
          command: |
            echo "nothing to do!"
  
  deploy:
    docker:
      - image: circleci/ruby:2.6
        # aws_auth:
        #   aws_access_key_id: AKIAQWERVA
        #   aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    # working_directory: ~/portfolio
    steps:
      # - add_ssh_keys:
          # fingerprints: "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
      # - run:
      #     name: Disable SSH StrictHostKeyChecking
      #     command: |
      #       cat <<EOF >> $HOME/.ssh/config
      #       Host *
      #         StrictHostKeyChecking no
      #       EOF
      - checkout
      - run:
          name: Install system packages
          command: |
            sudo apt-get update
            # sudo apt-get install -y       #libmysqlclient-dev libmagickwand-dev imagemagick
            gem install bundler -v 1.17.2
      - restore_cache: #キャッシュの利用
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "webapp/Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install dependencies
          command: |
            cd webapp
            bundle install --path=vendor/bundle --clean
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "webapp/Gemfile.lock" }}
          paths:
            - webapp/vendor/bundle
      - run:
          name: Deploy to staging
          command: |
            cd webapp
            # bundle exec cap staging deploy
